### ISSUE TITLE
Career-related templates

### ISSUE THREAD

**Issue by ivov** [shu8/mlh-fellowship-0.2.1-halfway-hackathon#14]
We need to write down all the career-related templates for fellows:
- Blitz pitch template
- Casual e-mail template
- Challenge submission template
- Cover letter template
- CV section template
- LinkedIn message template
- Post-application followup template

**Comment by shu8** [comment]
Closed by https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/41
