### ISSUE TITLE
Most Valuable Fellow

### ISSUE THREAD

**Issue by ivov** [shu8/mlh-fellowship-0.2.1-halfway-hackathon#15]
We should implement a feature whereby every Friday we count everyone's commits for the week, and then our Discord bot issues shoutout using `@fellow` congratulating that fellow for everyone to hear.

Implementation:
- [x] Collect everyone's commits for the past week, maybe using GitHub's new [Commit Search API](https://developer.github.com/v3/search/#search-commits), and then return the fellow with the highest `total_count`. Allowances should be made for `incomplete_results: true`.
- [x] Space out requests because of GitHub Custom Search API rate limit.
- [x] Set up Lambda function to run every Friday at a fixed time, and send a post request to a webhook in our Discord channel.
- [ ] Set up the webhook on Discord.
- [ ] Request permission to use `@fellow`.

**Comment by ivov** [comment]
Draft PR #17 addresses step 1.

**Comment by ivov** [comment]
It appears the Custom Search API has a [custom rate limit](https://developer.github.com/v3/search/#rate-limit):

> For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute. For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute.

We have ~160 users, so we'll have to look into how to work around this - maybe slowing down calls to retrieve everyone in 6 minutes or so.

**Comment by ivov** [comment]
Spacing out of requests added with https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/17/commits/44570c495038349a48690ab6ff630b5534b92d87.

**Comment by shu8** [comment]
https://docs.github.com/en/github/searching-for-information-on-github/searching-in-forks

> Forks are only indexed for code search when they have more stars than the parent repository. You will not be able to search the code in a fork that has less stars than its parent. To show forks with more stars than the parent repository in code search results, add fork:true or fork:only to your query.

It looks like we might have a problem with people who are working in forks (e.g. for the hackathon). Our current system will only work for commits that are in a non-fork (unless the fork has a lot of stars!). For the most part, I don't think this will be a problem though.

**Comment by shu8** [comment]
Lambda integration added and tested as of https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/17/commits/112e9cf33e8d8f684de66ff95dc2eafd21ae7d5c

**Comment by shu8** [comment]
> Request permission to use @fellow.

Is this something we need to do in the discord server?

**Comment by ivov** [comment]
It's likely reserved for admins, I'll find out.

**Comment by ivov** [comment]
This is done!
