### ISSUE TITLE
Create a Webapp

### ISSUE THREAD

**Issue by kendevops** [shu8/mlh-fellowship-0.2.1-halfway-hackathon#18]
- [x] Overall structure with [GitHub Primer design system](https://primer.style/components/)
- [x] Overview page
- [x] Pod page
- [x] Fellow page
  - main data, contributions data, latest standups
  - standups streak?
- [x] Jobhunt list page
  - Site, hyperlink, logo/favicon  
- [x] Jobhunt templates page
   - 7 templates
- [x] Jobhunt exchange page
  - Star fellow's GitHub repo
  - Post recommendation on fellow's LinkedIn profile
  - Invite logged-in user to add skills to own profile

**Comment by shu8** [comment]
> Invite logged-in user to add skills to own profile

Let's do this post-hackathon, as we don't have time right now

**Comment by shu8** [comment]
Done as of the recent PRs:

- https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/45
- https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/52
- https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/51
- https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/50
