### ISSUE TITLE
Create portfolio page

### ISSUE THREAD

**Issue by shu8** [shu8/mlh-fellowship-0.2.1-halfway-hackathon#38]
We want to be able to demonstrate a Fellow/Mentor's contributions and summary of them.

We could show:

- [x] pod
- [x] username
- [x] recent pull requests
- [x] recent issues
- [x] standups
- [x] link to linkedin
- [x] link to github

amongst possibly others

We'll probably include the whole exchange system into the portfolio

**Comment by ivov** [comment]
Agreed, the exchange system should be integrated, not be a standalone section.

**Comment by shu8** [comment]
Adding the final few things now:

- name
- github URL
- linkedin URL

**Comment by shu8** [comment]
Done as of e8d3b8b3f72f1a5cec59c1c6466e1469a4b0f6d1
