### ISSUE TITLE
Retrieve repos to be starred

### ISSUE THREAD

**Issue by ivov** [shu8/mlh-fellowship-0.2.1-halfway-hackathon#4]
We need a quick way to retrieve a user's repos and, from those, to select the first pinned repo or otherwise a random repo. The selected repo is the one we will invite the logged-in user to star from our platform.

There seems to be a `pinnedItems` property [in the GitHub GraphQL API](https://developer.github.com/v4/object/user/).

**Comment by ivov** [comment]
This standalone function is done, but it will be added once the web app structure is in place.

**Comment by shu8** [comment]
Done as of https://github.com/shu8/mlh-fellowship-0.2.1-halfway-hackathon/pull/45
